"""empty message

Revision ID: 6864245b16b9
Revises: a1dee83022d7
Create Date: 2021-09-01 19:40:35.947231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6864245b16b9'
down_revision = 'a1dee83022d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social')
    op.drop_table('users_socials')
    op.add_column('users', sa.Column('github_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('mailru_id', sa.String(length=128), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['github_id'])
    op.create_unique_constraint(None, 'users', ['mailru_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'mailru_id')
    op.drop_column('users', 'github_id')
    op.create_table('users_socials',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('social_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['social_id'], ['social.id'], name='users_socials_social_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_socials_user_id_fkey')
    )
    op.create_table('social',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='social_pkey')
    )
    # ### end Alembic commands ###
