"""empty message

Revision ID: a1dee83022d7
Revises: e9edb5f3952a
Create Date: 2021-08-30 08:55:36.342180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1dee83022d7'
down_revision = 'e9edb5f3952a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_socials',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('social_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['social_id'], ['social.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_constraint('social_user_id_key', 'social', type_='unique')
    op.drop_constraint('social_user_id_fkey', 'social', type_='foreignkey')
    op.drop_column('social', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('social_user_id_fkey', 'social', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('social_user_id_key', 'social', ['user_id'])
    op.drop_table('users_socials')
    # ### end Alembic commands ###
