"""empty message

Revision ID: ab08ffa4a509
Revises: cd54bef85e34
Create Date: 2021-08-20 20:06:25.646478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab08ffa4a509'
down_revision = 'cd54bef85e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
